version: '3.2'
services:
  ws:
    build: web_services
    depends_on:
      - db
    network_mode: host
    image: web_services
    env_file:
      - config.env
    expose:
      - 3000

#  scorer:
#    build: scorer
#    depends_on:
#      - ws
#      - db
#    network_mode: host
#    image: brightid/scorer
#    volumes:
#      - type: volume
#        source: snapshots
#        target: /snapshots
#    env_file:
#      - config.env
#    environment:
#      - INIT_BRIGHTID_DB
#
  consensus:
    build: consensus
    depends_on:
      - ws
      - db
    network_mode: host
    image: consensus
    volumes:
      - type: volume
        source: snapshots
        target: /snapshots
    env_file:
      - config.env

  db:
    build: db
    network_mode: host
    image: brightid/db
    volumes:
      - "data:/var/lib/arangodb3"
      - "apps:/var/lib/arangodb3-apps"
    env_file:
      - config.env
    environment:
      - INIT_BRIGHTID_DB
    expose:
      - 8529

  web:
    image: nginx
    volumes:
      - ./web/brightid-nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
    env_file:
      - config.env

volumes:
  snapshots:
  data:
  apps:
